---
- name: Load rhcos.json from openshift/installer GitHub repository
  uri:
    url: "https://raw.githubusercontent.com/openshift/installer/release-{{ ocp_installer_version }}/data/data/rhcos.json"
  register: rhcos_json
  no_log: true

- name: Extract URL of the RHCOS OpenStack image
  set_fact:
    rhcos_osp_image_url: "{{ rhcos_json.json.baseURI + rhcos_json.json.images.openstack.path }}"

- name: Download compressed RHCOS image
  get_url:
    url: "{{ rhcos_osp_image_url }}"
    dest: "{{ install_dir }}"
  register: rhcos_download

- name: Extract RHCOS image
  command:  "gunzip {{ rhcos_download.dest }}"
  register: rhcos_extract

- name: Register RHCOS image path
  set_fact:
    rhcos_image_path: "{{ (rhcos_download.dest | splitext)[0] }}"
