---
- name: Register pull secret
  set_fact:
    pull_secret: "{{ lookup('file', pull_secret_file) }}"
  no_log: true

- name: Create installation configuration file
  template:
    src: install-config.j2
    dest: "{{ install_dir }}/{{ install_config_file }}"

- name: Copy configuration file to resources sub-direcotry
  copy:
    remote_src: true
    src: "{{ install_dir }}/{{ install_config_file }}"
    dest: "{{ resources_subdir }}/"