---
# tasks file for ovirt.ocp4-ipi

# TODO: Fail early if we don't have DNS records

- name: Prepare oVirt engine as the installer machine
  include_tasks: prepare_engine.yml

- name: Perform OCP installation
  include_tasks: ocp_install.yml