---
# tasks file for ovirt.ocp4-ipi

- name: Check DNS records
  include_tasks: dns_check.yml
  when: perform_dns_check

- name: Prepare oVirt engine as the installer machine
  include_tasks: prepare_engine.yml

- name: Perform OCP installation
  include_tasks: ocp_install.yml