---
# tasks file for ovirt.ocp4-ipi
- name: Early checks
  include_tasks: early_checks.yml

- name: Prepare custom RHCOS template.yml
  include_tasks: custom_rhcos.yml
  when: prepare_custom_rhcos_template

- name: Check DNS records
  include_tasks: dns_check.yml
  when: perform_dns_check

- name: Prepare oVirt engine as the installer machine
  include_tasks: prepare_engine.yml

- name: Perform OCP installation
  include_tasks: ocp_install.yml
  when: not stop_before_installation