---
# tasks file for ovirt.ocp4-ipi
- name: Prepare oVirt engine as the installer machine
  include_tasks: prepare_engine.yml

- name: Upload custom RHCOS template
  include_tasks: upload_custom_rhcos.yml
  when: rhcos_use_custom_template
