---
- name: Print message about installation log
  debug:
    msg: "The installation is starting. You can follow its progress in {{ resources_subdir }}/{{ installer_log_file }}"

- block:
    - name: Install OpenShift {{ ocp_installer_version }} on oVirt
      shell: >-
        {{ install_dir }}/{{ installer_binary }} create cluster
        --dir={{ resources_subdir }} --log-level={{ ocp_installer_log_level }}
      environment:
        OVIRT_CONFIG: "{{ install_dir }}/{{ ovirt_credentials_file }}"
        TF_LOG: "{{ terraform_log_level }}"
      register: ocp_install_result
      no_log: true

  rescue:
    - name: Print OCP installation log
      debug:
        var: ocp_install_result.stderr_lines

    - name: Fail on unsuccessful installation
      fail:
        msg: OpenShift installer returned non-zero return code