---
- name: Link oVirt CA certificate to {{ trusted_ca_dir }}
  file:
    state: link
    src: "{{ engine_cafile }}"
    dest: "{{ trusted_ca_dir }}/{{ engine_ca }}"
  notify: Update CA trust

- name: Load oVirt CA certificate content
  command: "cat {{ engine_cafile }}"
  register: engine_ca_content
  no_log: true
  changed_when: false

- name: Create oVirt credentials file
  template:
    dest: "{{ install_dir }}/{{ ovirt_credentials_file }}"
    src: ovirt-config.j2

- name: Execute handlers to update CA trust if necessary
  meta: flush_handlers