---
- name: Link oVirt CA certificate to {{ trusted_ca_dir }}
  file:
    state: link
    src: "{{ engine_cafile }}"
    dest: "{{ trusted_ca_dir }}/{{ engine_ca }}"
  register: link_ca

- name: Update CA trust
  command: /bin/update-ca-trust
  when: link_ca.changed

- name: Load oVirt CA certificate content
  shell: "cat {{ engine_cafile }}"
  register: engine_ca_content
  no_log: true

- name: Create oVirt credentials file
  template:
    dest: "{{ install_dir }}/{{ ovirt_credentials_file }}"
    src: ovirt-config.j2