---
- name: Link oVirt CA certificate to {{ trusted_ca_dir }}
  file:
    state: link
    src: "{{ engine_ca_path }}/{{ engine_ca }}"
    dest: "{{ trusted_ca_dir }}/{{ engine_ca }}"
  notify: Update CA trust

- name: Load oVirt CA certificate content
  shell: "cat {{ engine_ca_path }}/{{ engine_ca }}"
  register: engine_ca_content
  no_log: true

- name: Create oVirt credentials file
  template:
    dest: "{{ install_dir }}/{{ ovirt_credentials_file }}"
    src: ovirt-config.j2