---
- name: Link oVirt CA certificate to {{ trusted_ca_dir }}
  file:
    state: link
    src: /etc/pki/ovirt-engine/ca.pem
    dest: "{{ trusted_ca_dir }}/ca.pem"
  notify: Update CA trust

- name: Create oVirt credentials file
  template:
    dest: "{{ install_dir }}/ovirt-config.yml"
    src: ovirt-config.j2